name: Playwright Tests
on:
  #push:  #disabled to avoid running tests on every push, can be enabled if needed
    #branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: #Events for manually triggering the workflow from the Actions tab in GitHub UI
  #schedule: # to schedule the workflow to run at specific UTC time
    #- cron: '0 0 * * *'  # Runs daily at 00:00 UTC
jobs:
  test:
    timeout-minutes: 10 #timeout after 10 minutes to prevent hanging workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore PlaywrightAutomation/PlaywrightAutomation.csproj
      - name: Build project
        run: dotnet build PlaywrightAutomation/PlaywrightAutomation.csproj --configuration Release --no-restore
      - name: Install Playwright Browsers
        run: pwsh PlaywrightAutomation/bin/Release/net8.0/playwright.ps1 install --with-deps
      - name: Run Playwright tests
        run: dotnet test PlaywrightAutomation/PlaywrightAutomation.csproj --logger:"Playwright;LogDir=playwright-report" --no-build --configuration Release
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30 #Saves test reports for 30 days
